# Generated by Django 2.2.3 on 2019-07-06 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='f_name',
            new_name='Current_City',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='l_name',
            new_name='Github_Link',
        ),
        migrations.AddField(
            model_name='customuser',
            name='Linkedin_link',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='MSc_Institute_Country',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='MSc_Institute_name',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='MSc_end_date',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='MSc_start_date',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Phd_Institute_Country',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Phd_Institute_name',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Phd_end_date',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Phd_start_date',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to='student/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='about_me',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='blood_group',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_no',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cur_semester',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='height',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='home_town',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='session',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skill_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sust_reg_no',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weight',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('alumni_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('Research_area', models.CharField(blank=True, default=None, max_length=55, null=True)),
                ('Published_Paper', models.CharField(blank=True, default=None, max_length=55, null=True)),
                ('Published_Journal', models.CharField(blank=True, default=None, max_length=55, null=True)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('Job_Institute_or_Company', models.CharField(blank=True, default=None, max_length=55, null=True)),
                ('Address', models.CharField(blank=True, default=None, max_length=55, null=True)),
                ('Job_Position', models.CharField(blank=True, default=None, max_length=55, null=True)),
                ('Job_start_date', models.CharField(blank=True, default=None, max_length=55, null=True)),
                ('Job_end_date', models.CharField(blank=True, default=None, max_length=55, null=True)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
