# Generated by Django 2.2.3 on 2019-07-07 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eee', '0002_auto_20190706_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Picture',
        ),
    ]
