# Generated by Django 2.2.3 on 2019-07-07 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eee', '0004_customuser_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='photos',
        ),
    ]
